# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Junior Design Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  #pod for google sign in

  pod 'GoogleSignIn'

  # Pods for Junior Design Project

end
